require:
  - rubocop-rails

AllCops:
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
