matrix:
  include:
    - language: ruby
      rvm:
        - 2.7.2
      before_install:
        - nvm install 15.0.1
      install:
        - gem install bundler
        - bundle install
        - yarn install
        - NODE_ENV=test bundle exec rails webpacker:compile
      script:
        - bundle exec rubocop
        - bundle exec rspec
    - language: node_js
      node_js:
        - 15.0.1
      install:
        - yarn install
      script:
        - yarn run lint
