matrix:
  include:
    - language: ruby
      rvm:
        - 2.7.2
      install:
        - gem install bundler
        - bundle install
      script:
        - bundle exec rubocop
        - bundle exec rspec
    - language: node_js
      node_js:
        - 15.0.1
      install:
        - yarn install
      script:
        - yarn run lint
